// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18034
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ResearchLinks.SpecTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Projects API V2")]
    public partial class ProjectsAPIV2Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ProjectsAPI_V2.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Projects API V2", "In order to support the new IsUrgent Feature in V2\r\nAs a client of the Web Api\r\nI" +
                    " want to be able to Create and Update projects with the IsUrgent Property", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a new project saves posted values including IsUrgent")]
        public virtual void CreateANewProjectSavesPostedValuesIncludingIsUrgent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a new project saves posted values including IsUrgent", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "Name",
                        "Test Project"});
            table1.AddRow(new string[] {
                        "Description",
                        "Test Description"});
            table1.AddRow(new string[] {
                        "IsUrgent",
                        "True"});
            table1.AddRow(new string[] {
                        "UserName",
                        "james"});
            table1.AddRow(new string[] {
                        "Password",
                        "james2013"});
#line 7
 testRunner.Given("the following project inputs and authentication", ((string)(null)), table1, "Given ");
#line 14
 testRunner.When("the client posts the inputs to the website for V2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then("a Created status should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
 testRunner.When("the client gets the project by header location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.Then("the saved project matches the inputs including IsUrgent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a new project where IsUrgent is missing returns bad request")]
        public virtual void CreateANewProjectWhereIsUrgentIsMissingReturnsBadRequest()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a new project where IsUrgent is missing returns bad request", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "Name",
                        "Test Project"});
            table2.AddRow(new string[] {
                        "Description",
                        "Test Description"});
            table2.AddRow(new string[] {
                        "UserName",
                        "james"});
            table2.AddRow(new string[] {
                        "Password",
                        "james2013"});
#line 20
 testRunner.Given("the following project inputs and authentication", ((string)(null)), table2, "Given ");
#line 26
 testRunner.When("the client posts the inputs to the website for V2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
 testRunner.Then("a BadRequest status should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Put project saves put values with edited IsUrgent")]
        public virtual void PutProjectSavesPutValuesWithEditedIsUrgent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Put project saves put values with edited IsUrgent", ((string[])(null)));
#line 29
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "Name",
                        "Test Project"});
            table3.AddRow(new string[] {
                        "Description",
                        "Test Description"});
            table3.AddRow(new string[] {
                        "IsUrgent",
                        "True"});
            table3.AddRow(new string[] {
                        "UserName",
                        "james"});
            table3.AddRow(new string[] {
                        "Password",
                        "james2013"});
#line 30
 testRunner.Given("the following project inputs and authentication", ((string)(null)), table3, "Given ");
#line 37
 testRunner.When("the client posts the inputs to the website for V2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.Then("a Created status should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
 testRunner.When("the client gets the project by header location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
 testRunner.Then("the saved project matches the inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "Name",
                        "Test Project Edited"});
            table4.AddRow(new string[] {
                        "Description",
                        "Test Description Edited"});
            table4.AddRow(new string[] {
                        "IsUrgent",
                        "False"});
            table4.AddRow(new string[] {
                        "UserName",
                        "james"});
            table4.AddRow(new string[] {
                        "Password",
                        "james2013"});
#line 41
 testRunner.Given("the following project inputs and authentication", ((string)(null)), table4, "Given ");
#line 48
 testRunner.When("the client puts the inputs to the website for V2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("a OK status should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 50
 testRunner.When("the client gets the project by header location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 51
 testRunner.Then("the saved project matches the inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Put project where IsUrgent is missing returns bad request")]
        public virtual void PutProjectWhereIsUrgentIsMissingReturnsBadRequest()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Put project where IsUrgent is missing returns bad request", ((string[])(null)));
#line 54
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Name",
                        "Test Project"});
            table5.AddRow(new string[] {
                        "Description",
                        "Test Description"});
            table5.AddRow(new string[] {
                        "IsUrgent",
                        "True"});
            table5.AddRow(new string[] {
                        "UserName",
                        "james"});
            table5.AddRow(new string[] {
                        "Password",
                        "james2013"});
#line 55
 testRunner.Given("the following project inputs and authentication", ((string)(null)), table5, "Given ");
#line 62
 testRunner.When("the client posts the inputs to the website for V2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
 testRunner.Then("a Created status should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 64
 testRunner.When("the client gets the project by header location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
 testRunner.Then("the saved project matches the inputs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "Name",
                        "Test Project Edited"});
            table6.AddRow(new string[] {
                        "Description",
                        "Test Description Edited"});
            table6.AddRow(new string[] {
                        "UserName",
                        "james"});
            table6.AddRow(new string[] {
                        "Password",
                        "james2013"});
#line 66
 testRunner.Given("the following project inputs and authentication", ((string)(null)), table6, "Given ");
#line 72
 testRunner.When("the client puts the inputs to the website for V2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
 testRunner.Then("a BadRequest status should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
